#!/usr/bin/env python3
"""FastAPI server for the devtest app.

Four routes and nothing else: login, context refresh, the dispatcher that
carries every other operation, and info — registered by `srv.register_fastapi`
on the application itself, because this file *is* the application. Plugin
loading, model generation and the seed data come from devtest.py, so the test
harness and the server always run the same application — importing it also
registers the endpoints it declares.

Run from this directory:  python server_fastapi.py
"""
import os

from fastapi import FastAPI

import devtest  # also puts the coframe package on sys.path  # noqa: E402
import coframe.server_utils as srv  # noqa: E402

# ── Application ─────────────────────────────────────────────────────────────

# Listening is the application's choice: the library only speaks. Stdout is
# the terminal here and journald under systemd; COFRAME_LOG_FILE adds a file.
srv.setup_logging(os.environ.get('COFRAME_LOG_LEVEL', 'INFO'),
                  os.environ.get('COFRAME_LOG_FILE'))

coframe_app, plugins = devtest.setup()

import model  # type: ignore  # generated by devtest.setup()  # noqa: E402

coframe_app.initialize_db(plugins.config["db_engine"], model)
plugins.load_all_locales()
devtest.seed(coframe_app, model)

# 32 bytes at least: below that PyJWT warns that the key is weak for
# HS256, and a warning nobody can act on is a warning people learn to skip.
SECRET_KEY = os.environ.get("SECRET_KEY", "development-secret-key-not-for-service")

app = FastAPI(
    title="Coframe devtest",
    description="Sandbox app of the framework",
    version=plugins.config.get("version", "0.0.0"),
)

# ── Routes ──────────────────────────────────────────────────────────────────

srv.register_fastapi(app, coframe_app, plugins, SECRET_KEY)


# A built client, when there is one: `clientui/`, mounted where `client:` in
# config.yaml says - at the root, devtest being the application itself. Last,
# so the API routes win.
srv.serve_client_fastapi(app, os.path.dirname(os.path.abspath(__file__)), plugins.config)


if __name__ == "__main__":
    import uvicorn

    port = plugins.config.get("api", {}).get("port", 8300)
    print(f"\n🚀 Coframe devtest on port {port}")
    print(f"📖 OpenAPI docs: http://localhost:{port}/docs\n")
    uvicorn.run(app, host="0.0.0.0", port=port, log_level="info")
