#!/usr/bin/env python3
"""Flask server for the devtest app.

The same four routes as the FastAPI server, registered by the same call:
`srv.register_flask` puts login, context refresh, the dispatcher and info on
whatever it is given — here the application itself, because this file *is* the
application. Plugin loading, model generation and the seed data come from
devtest.py, so both servers and the test harness run the same application.

Run from this directory:  python server_flask.py
"""
import os

from flask import Flask, send_from_directory
from flask_cors import CORS

import devtest  # also puts the coframe package on sys.path  # noqa: E402
import coframe.server_utils as srv  # noqa: E402

# ── Application ─────────────────────────────────────────────────────────────

coframe_app, plugins = devtest.setup()

import model  # type: ignore  # generated by devtest.setup()  # noqa: E402

coframe_app.initialize_db(plugins.config["db_engine"], model)
plugins.load_all_locales()
devtest.seed(coframe_app, model)

# 32 bytes at least: below that PyJWT warns that the key is weak for
# HS256, and a warning nobody can act on is a warning people learn to skip.
SECRET_KEY = os.environ.get("SECRET_KEY", "development-secret-key-not-for-service")

app = Flask(__name__)
app.config["SECRET_KEY"] = SECRET_KEY
# expose_headers: the refresh token travels in a response header, and a
# browser hides those from JS across origins — which is what dev is, with
# the Vite server on a port of its own. Without it the client never sees a
# refreshed token in development, silently.
CORS(app, expose_headers=["X-New-Token"])

# ── Routes ──────────────────────────────────────────────────────────────────

srv.register_flask(app, coframe_app, plugins, SECRET_KEY)


# A built client, when there is one — registered last so the API routes win.
# The catch-all serves index.html for unknown paths, as a SPA needs.
if os.path.isdir("static_client"):

    @app.route("/", defaults={"path": ""})
    @app.route("/<path:path>")
    def client(path):
        if path and os.path.isfile(os.path.join("static_client", path)):
            return send_from_directory("static_client", path)
        return send_from_directory("static_client", "index.html")


if __name__ == "__main__":
    port = plugins.config.get("api", {}).get("port", 8300)
    print(f"\n🚀 Coframe devtest (Flask) on port {port}\n")
    app.run(host="0.0.0.0", port=port)
